name: Changelog Generator
on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]

jobs:
  changelog:
    name: Chanegelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: etcdigital/pull-request-changelog@master
        with:
          token: ${{ secrets.GH_WORKFLOW_CHANGELOG }}