name: Enforce Merge Source Branch

on:
  pull_request:
    branches:
      - main  # Replace with your protected branch name

jobs:
  restrict-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.base_ref }}" != "main" || "${{ github.head_ref }}" != "develop" ]]; then
            echo "Pull requests to main must originate from develop."
            exit 1
          fi
        shell: bash
